//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportIssue
{
    using System;
    using System.Collections.Generic;
    
    public partial class Filter
    {
        public string ID { get; set; }
        public string Issue { get; set; }
        public string Product { get; set; }
        public string Wrong { get; set; }
        public string Right { get; set; }
        public string Submitted { get; set; }
        public string Fixed { get; set; }
        public string Status { get; set; }
    }
}
