//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportIssue
{
    using System;
    using System.Collections.Generic;
    
    public partial class Issue
    {
        public string ID { get; set; }
        public string Template { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public string Parameter1 { get; set; }
        public string Parameter2 { get; set; }
        public string Parameter3 { get; set; }
        public string Parameter4 { get; set; }
        public string Parameter5 { get; set; }
        public string Parameter6 { get; set; }
        public string Parameter7 { get; set; }
        public string Parameter8 { get; set; }
        public string Parameter10 { get; set; }
        public string Parameter9 { get; set; }
        public string Parameter11 { get; set; }
        public string Parameter12 { get; set; }
        public string Parameter13 { get; set; }
        public string Parameter14 { get; set; }
        public string Parameter15 { get; set; }
        public string Parameter16 { get; set; }
        public string Parameter17 { get; set; }
        public string Parameter18 { get; set; }
        public string Parameter19 { get; set; }
        public string Parameter20 { get; set; }
        public string Url { get; set; }
        public string BugPath { get; set; }
        public string MarkersString { get; set; }
        public bool Fixed { get; set; }
        public bool Submitted { get; set; }
        public string Product { get; set; }
        public string Reason { get; set; }
        public string Wrong { get; set; }
        public string WhereFound { get; set; }
        public string Right { get; set; }
        public string English { get; set; }
        public string IssueTxt { get; set; }
        public byte[] PictureBytes { get; set; }
    }
}
